// Generated by CoffeeScript 1.8.0
(function() {
  var bowerFiles, coffee, connect, gulp, gulpFilter, jade, minifycss, prettify, rename, stylus, uglify;

  gulp = require('gulp');

  connect = require('gulp-connect');

  jade = require('gulp-jade');

  stylus = require('gulp-stylus');

  coffee = require('gulp-coffee');

  prettify = require('gulp-prettify');

  uglify = require('gulp-uglify');

  minifycss = require('gulp-minify-css');

  rename = require('gulp-rename');

  gulpFilter = require('gulp-filter');

  bowerFiles = require('main-bower-files');

  gulp.task('bower', function() {
    var cssFilter, fontFilter, jsFilter;
    jsFilter = gulpFilter('*.js');
    cssFilter = gulpFilter('*.css');
    fontFilter = gulpFilter(['*.eot', '*.woff', '*.svg', '*.ttf']);
    return gulp.src(bowerFiles()).pipe(jsFilter).pipe(gulp.dest('./app/vendor/js')).pipe(uglify()).pipe(rename({
      suffix: '.min'
    })).pipe(gulp.dest('./app/vendor/js')).pipe(jsFilter.restore()).pipe(cssFilter).pipe(gulp.dest('./app/vendor/css')).pipe(minifycss()).pipe(rename({
      suffix: '.min'
    })).pipe(gulp.dest('./app/vendor/css')).pipe(cssFilter.restore()).pipe(fontFilter).pipe(gulp.dest('./app/vendor/fonts'));
  });

  gulp.task('images', function() {
    return gulp.src('./images/*').pipe(gulp.dest('./app/images')).pipe(connect.reload());
  });

  gulp.task('connect', function() {
    return connect.server({
      port: 1337,
      livereload: true,
      root: './app'
    });
  });

  gulp.task('jade', function() {
    return gulp.src('./jade/*.jade').pipe(jade()).pipe(prettify({
      indent_size: 2
    })).pipe(gulp.dest('./app')).pipe(connect.reload());
  });

  gulp.task('stylus', function() {
    return gulp.src('./stylus/*.styl').pipe(stylus()).pipe(gulp.dest('./app/css')).pipe(minifycss()).pipe(rename({
      suffix: '.min'
    })).pipe(gulp.dest('./app/css')).pipe(connect.reload());
  });

  gulp.task('coffee', function() {
    return gulp.src('./coffee/*.coffee').pipe(coffee()).pipe(gulp.dest('./app/js')).pipe(uglify()).pipe(rename({
      suffix: '.min'
    })).pipe(gulp.dest('./app/js')).pipe(connect.reload());
  });

  gulp.task('watch', function() {
    gulp.watch('./jade/*.jade', ['jade']);
    gulp.watch('./stylus/*.styl', ['stylus']);
    gulp.watch('./coffee/*.coffee', ['coffee']);
    return gulp.watch('./images/*', ['images']);
  });

  gulp.task('default', ['connect', 'watch', 'jade', 'stylus', 'coffee', 'images']);

}).call(this);
