// Generated by CoffeeScript 1.8.0
(function() {
  var coffee, connect, gulp, jade, mainBowerFiles, prettify, stylus;

  gulp = require('gulp');

  connect = require('gulp-connect');

  jade = require('gulp-jade');

  stylus = require('gulp-stylus');

  coffee = require('gulp-coffee');

  prettify = require('gulp-prettify');

  mainBowerFiles = require('main-bower-files');

  gulp.task('images', function() {
    return gulp.src('images/*').pipe(gulp.dest('app/images')).pipe(connect.reload());
  });

  gulp.task('bower', function() {
    return gulp.src(mainBowerFiles()).pipe(gulp.dest('app/bower'));
  });

  gulp.task('connect', function() {
    return connect.server({
      port: 1337,
      livereload: true,
      root: 'app'
    });
  });

  gulp.task('jade', function() {
    return gulp.src('jade/*.jade').pipe(jade()).pipe(prettify({
      indent_size: 2
    })).pipe(gulp.dest('app')).pipe(connect.reload());
  });

  gulp.task('stylus', function() {
    return gulp.src('stylus/*.styl').pipe(stylus()).pipe(gulp.dest('app/css')).pipe(connect.reload());
  });

  gulp.task('coffee', function() {
    return gulp.src('coffee/*.coffee').pipe(coffee()).pipe(gulp.dest('app/js')).pipe(connect.reload());
  });

  gulp.task('watch', function() {
    gulp.watch('jade/*.jade', ['jade']);
    gulp.watch('stylus/*.styl', ['stylus']);
    gulp.watch('coffee/*.coffee', ['coffee']);
    return gulp.watch('images/*', ['images']);
  });

  gulp.task('default', ['connect', 'watch', 'jade', 'stylus', 'coffee', 'bower', 'images']);

}).call(this);
